# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: lahirumadushan
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-lambda-api

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  environment:
    WM_USERNAME: ${env:WM_USERNAME}
    WM_PASSWORD: ${env:WM_PASSWORD}
    WM_BASE_URL: ${env:WM_BASE_URL, 'qa-partnerapi.watermetrics.co.nz:8095'}
    WM_TEST_BASE_URL: ${env:WM_TEST_BASE_UR, 'https://jsonplaceholder.typicode.com'}

functions:
  login:
    handler: handler.login
    events:
      - httpApi: 'POST /apiV2/Login'

  getSites:
    handler: handler.getSites
    events:
      - httpApi: 'GET /apiV2/GetMySitesAndMeasures'

  getData:
    handler: handler.getData
    events:
      - httpApi: 'GET /apiV2/GetData/{proxy+}'

  logoff:
    handler: handler.logoff
    events:
      - httpApi: 'POST /apiV2/Logoff'

  getDummyData:
    handler: handler.getDummyData
    events:
      - httpApi: 'GET /todos/{proxy+}'